[package]
name = "socksproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
base64 = "0.13.1"
cipher = "0.4.3"
rust-crypto = "0.2.36"
